=== IceTegliaf/ipython_ru/docs/test_format_dox.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns=http://www.ipython.ru" targetNamespace="http://www.ipython.ru">
	

    <complexType name="packages">
    	<sequence>
    		<element name="package" type="package"></element>
    	</sequence>
    </complexType>

    <element name="ipython_ru_dox" type="packages"></element>


    <complexType name="package">
    	<sequence>
    		<element name="doc" type="doc" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="attribute" type="attribute" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    		<element name="method" type="method" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    		<element name="class" type="class"></element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="version" type="string" use="optional"></attribute>
    	<attribute name="file" type="string" use="optional"></attribute>
    </complexType>
    
    <simpleType name="doc">
    	<restriction base="string"></restriction>
    </simpleType>

    <complexType name="attribute"><complexContent><restriction base="string">
    		<attribute name="name" type="string" use="required"></attribute>
    		<attribute name="type" type="string" use="optional"></attribute>
    		<attribute name="value" type="string" use="optional"></attribute>
    </restriction></complexContent></complexType>

    <complexType name="argument"><complexContent><restriction base="string">
    		<attribute name="name" type="string" use="required"></attribute>
    		<attribute name="type" type="string" use="optional"></attribute>
    		<attribute name="value" type="string" use="optional"></attribute>
    </restriction></complexContent></complexType>

    <complexType name="method">
    	<sequence>
    		<element name="doc" type="string" minOccurs="0" maxOccurs="1"></element>
    		<element name="argument" type="argument" minOccurs="0" maxOccurs="unbounded"></element>
    		<element name="return" type="string" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    </complexType>


    <complexType name="class">
    	<sequence>
    		<element name="extend" maxOccurs="unbounded"
    			minOccurs="1">
    			<complexType>
    				<attribute name="name" type="string"
    					use="required">
    				</attribute>
    			</complexType>
    		</element>
    		<element name="doc" type="doc" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="attribute" type="attribute"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="method" type="method" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
</schema>

=== IceTegliaf/ipython_ru/docs/test_format_dox.xml
<!DOCTYPE ipython_ru_dox SYSTEM "ipython_ru_docx.dtd">
<!--example xml document for structure all module documentation-->
<ipython_ru_dox ver="1"
		xmlns="http://www.ipython.ru"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="test_format_dox.xsd">
	<package name="django.template" version="1.9.1release" file="django/template/__init__.py">
		<doc><![CDATA[This is the Django template system.
 
How it works:
 
The Lexer.tokenize() function converts a template string (i.e., a string containing
markup with custom template tags) to tokens, which can be either plain text
(TOKEN_TEXT), variables (TOKEN_VAR) or block statements (TOKEN_BLOCK).
 
The Parser() class takes a list of tokens in its constructor, and its parse()
method returns a compiled template -- which is, under the hood, a list of
Node objects.
 
Each Node is responsible for creating some sort of output -- e.g. simple text
(TextNode), variable values in a given context (VariableNode), results of basic
logic (IfNode), results of looping (ForNode), or anything else. The core Node
types are TextNode, VariableNode, IfNode and ForNode, but plugin modules can
define their own custom node types.
 
Each Node has a render() method, which takes a Context and returns a string of
the rendered node. For example, the render() method of a Variable Node returns
the variable's value as a string. The render() method of an IfNode returns the
rendered output of whatever was inside the loop, recursively.
 
The Template class is a convenient wrapper that takes care of template
compilation and rendering.
 
Usage:
 
The only thing you should ever use directly in this file is the Template class.
Create a compiled template object with a template_string, then call render()
with a context. In the compilation stage, the TemplateSyntaxError exception
will be raised if the template doesn't have proper syntax.
 
Sample code:
 
>>> from django import template
>>> s = u'<html>{% if test %}<h1>{{ varvalue }}</h1>{% endif %}</html>'
>>> t = template.Template(s)
 
(t is now a compiled template, and its render() method can be called multiple
times with multiple contexts)
 
>>> c = template.Context({'test':True, 'varvalue': 'Hello'})
>>> t.render(c)
u'<html><h1>Hello</h1></html>'
>>> c = template.Context({'test':False, 'varvalue': 'Hello'})
>>> t.render(c)
u'<html></html>'
		]]></doc>		
	
		<attribute name="ANYFORMAT" value="268435456" type="int">
			<doc>Info</doc>
		</attribute>
		<attribute name="BIG_ENDIAN" value="4321"/>
		
		<method name="function_name">
			<argument name="template_string">description info argument - for excample use 'reST' format analize for get this info</argument>
			<argument name="origin" type="NoneType" value="None"/>
			<argument name="name" type="str" value="&lt;Unknown Template&gt;"/>
			<doc><![CDATA[Display stage -- can be called many times]]></doc>
			<return>exists if using reST or equals</return>			
		</method>
		
		<class name="BaseForm">
			<extend name="django.utils.encoding.StrAndUnicode"/>
		
			<doc><![CDATA[Common base class for all exceptions]]></doc>
			
			
			<attribute name="BIG_ENDIAN" value="4321" type="int" doc="info"/>
			
			<method type="static" name="function_name">
				<argument name="template_string">description info argument - for excample use 'reST' format analize for get this info</argument>
				<argument name="origin" type="NoneType" value="None"/>
				<argument name="name" type="str" value="&lt;Unknown Template&gt;"/>
				<doc><![CDATA[Display stage -- can be called many times]]></doc>
				<return>exists if using reST or equals</return>			
			</method>
			
			<method type="class" name="function_class">
				<argument name="template_string">description info argument - for excample use 'reST' format analize for get this info</argument>
				<argument name="origin" type="NoneType" value="None"/>
				<argument name="name" type="str" value="&lt;Unknown Template&gt;"/>
				<doc><![CDATA[Display stage -- can be called many times]]></doc>
				<return>exists if using reST or equals</return>			
			</method>
			
			<method type="object" name="function_object">
				<argument name="template_string">description info argument - for excample use 'reST' format analize for get this info</argument>
				<argument name="origin" type="NoneType" value="None"/>
				<argument name="name" type="str" value="&lt;Unknown Template&gt;"/>
				<doc><![CDATA[Display stage -- can be called many times]]></doc>
				<return>exists if using reST or equals</return>
			</method>						
		</class>		
	</package>
	
	<package name="django.template.smartif">
		<doc><![CDATA[Parser and utilities for the smart 'if' tag]]></doc>		
	</package>	
</ipython_ru_dox>
